env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  # - plugin:functional/recommended
  - airbnb

plugins:
  - react
  # - functional
  - react-hooks

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures": 
    - jsx: true

rules:
  # import/prefer-default-export: 1
  no-trailing-spaces: 1
  comma-dangle: ["error", "objects": "always-multiline"]
  quote-props: ["error", "as-needed"]
  object-curly-newline: ["error", { "multiline": true, "minProperties": 4 } ]
  no-multiple-empty-lines: 1
  eol-last: 1
  arrow-body-style: 1
  # quotes: 1
  consistent-return: 2
  indent: ["error", 2, { "SwitchCase": 1 }]
  no-else-return: 1
  semi: [1, "always"]
  space-unary-ops: 2
  no-extra-semi: 1
  no-mixed-spaces-and-tabs: 1
  # react/prop-types: [0, { ignore: <ignore>, customValidators: <customValidator>, skipUndeclared: <skipUndeclared> }]
  react/react-in-jsx-scope: 0
  import/extensions: 0
  react/prop-types: 0
  # react/react-in-jsx-scope: 0
  # functional/no-conditional-statements: 0
  # functional/no-expression-statements: 0
  # functional/functional-parameters: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function", "unnamedComponents": "arrow-function" }]
  # react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }
  import/no-unresolved: 0
  no-param-reassign: 0